import { launchBrowser } from './browser.mjs'
const b = await launchBrowser()
const p = await b.newPage({ viewport: { width: 1280, height: 860 } })
await p.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await p.waitForTimeout(700)
await p.screenshot({ path: 'dist/_home.png' })
await p.goto('http://localhost:5173/juegos/tango', { waitUntil: 'networkidle' })
await p.waitForTimeout(400)
await p.getByRole('button', { name: /^6×6$/ }).click()
await p.getByRole('button', { name: /^Media$/ }).click()
await p.getByRole('button', { name: /^Jugar/ }).first().click()
await p.waitForTimeout(800)
const c = p.locator('button[role="gridcell"]:not([disabled])')
for (let i = 0; i < 4 && (await c.count()) > 0; i++) await c.nth(i).click()
await p.waitForTimeout(400)
await p.locator('.tango-board-frame, .board-frame, [role="grid"]').first().screenshot({ path: 'dist/_tango.png' })
await b.close()
